# Generated by Django 5.0 on 2023-12-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasktitle', models.CharField(max_length=200, verbose_name='Task Title')),
                ('taskdescription', models.CharField(max_length=200, verbose_name='Task Description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Task Completed')),
                ('task_assign_date', models.DateTimeField(verbose_name='Task Assign Date')),
                ('categories', models.ManyToManyField(to='category.categorymodel', verbose_name='Categories')),
            ],
        ),
    ]
