# Generated by Django 4.2.7 on 2023-12-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_fathers_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mame',
            new_name='name',
        ),
    ]
