# Generated by Django 5.0 on 2023-12-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice_model',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('s_class', models.IntegerField()),
            ],
        ),
    ]
