# Generated by Django 4.2.7 on 2023-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('Roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
