# Generated by Django 5.0 on 2024-01-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0002_catagory_slug'),
        ('post', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='catrgory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='catagories.catagory'),
        ),
    ]
